---
#- name: Include nftables service
#  include_tasks: nftables.yml

- name: Install Zookeeper
  include_tasks: zookeeper.yaml
  when: inventory_hostname in groups.kafka

- name: Install Kafka
  include_tasks: kafka.yaml
  when: inventory_hostname in groups.kafka
